"""One-sentence business descriptions for every ticker in our universe.

Used by the public dashboard to give viewers context on each holding.
Keep descriptions factual, specific, and under ~25 words each.
"""

DESCRIPTIONS: dict[str, str] = {
    # Technology (semi, AI, hardware)
    "NVDA": "Designer of GPUs and AI accelerators powering the majority of modern AI training and inference workloads.",
    "AMD": "Semiconductor company producing CPUs, GPUs, and AI accelerators competing with Intel and Nvidia in data center and PC markets.",
    "TSLA": "Electric vehicle and energy storage manufacturer with significant exposure to autonomous driving and robotics.",
    "SMCI": "Manufacturer of high-performance servers and storage systems used for AI training and data center buildouts.",
    "MRVL": "Semiconductor company focused on data infrastructure — custom silicon for hyperscalers and 5G networking.",
    "ARM": "Designer of energy-efficient chip architectures licensed across smartphones, data centers, and embedded devices.",
    "CRWD": "Cloud-native endpoint security platform used by enterprises to detect and respond to cyber threats.",
    "SNOW": "Cloud data platform enabling enterprises to store, query, and share data across AWS, Azure, and GCP.",
    "PLTR": "Data and AI software platform serving defense, intelligence, and commercial customers with large-scale analytics.",
    "NET": "Cloudflare — edge computing and security network accelerating and protecting a large portion of internet traffic.",
    "SHOP": "E-commerce platform powering direct-to-consumer online stores and omnichannel retail.",
    "SQ": "Block — financial services platform operating Cash App, Square merchant services, and bitcoin infrastructure.",
    "COIN": "Largest US-regulated cryptocurrency exchange offering trading, custody, and institutional services.",
    "MSTR": "MicroStrategy — enterprise software company that holds the largest corporate bitcoin treasury.",
    "IONQ": "Quantum computing company building trapped-ion quantum processors accessed via cloud partnerships.",
    "RGTI": "Rigetti Computing — quantum computing company developing superconducting quantum processors and cloud services.",
    "APP": "AppLovin — mobile app marketing and monetization platform powered by AI-driven ad optimization.",
    "RKLB": "Rocket Lab — small-satellite launch provider and spacecraft manufacturer serving commercial and government customers.",
    "AFRM": "Buy-now-pay-later lender offering installment payments at online and in-store checkout.",
    "U": "Unity Software — real-time 3D development platform used by game studios, industrial designers, and filmmakers.",
    "DDOG": "Datadog — observability platform for monitoring cloud infrastructure, applications, and security events.",
    "MDB": "MongoDB — developer-focused document database offered as a managed cloud service and on-prem software.",
    "CFLT": "Confluent — streaming data platform built on Apache Kafka for real-time enterprise data pipelines.",
    "PATH": "UiPath — enterprise robotic process automation (RPA) platform for automating repetitive business workflows.",

    # Software (SaaS, DevTools, Security)
    "CRM": "Salesforce — dominant cloud CRM platform with expanding footprint in analytics, marketing, and AI agents.",
    "NOW": "ServiceNow — enterprise workflow automation platform for IT service management and adjacent functions.",
    "WDAY": "Workday — cloud HR and financial management software for large enterprises.",
    "ZS": "Zscaler — cloud-native security platform delivering zero-trust network access and secure web gateways.",
    "PANW": "Palo Alto Networks — enterprise cybersecurity leader in firewalls, cloud security, and SOC automation.",
    "FTNT": "Fortinet — network security vendor known for firewalls, SD-WAN, and integrated security fabric.",
    "OKTA": "Identity and access management platform providing single sign-on and workforce identity for enterprises.",
    "S": "SentinelOne — AI-driven endpoint security platform competing with CrowdStrike for enterprise SOC spend.",
    "BILL": "BILL Holdings — financial operations platform automating accounts payable, receivable, and spend for SMBs.",
    "HUBS": "HubSpot — CRM, marketing, and customer service software tailored for small and mid-sized businesses.",
    "VEEV": "Veeva — vertical SaaS leader providing CRM and cloud software to life sciences and pharma companies.",
    "PAYC": "Paycom — single-database human capital management and payroll platform for mid-sized employers.",
    "PCOR": "Procore — construction management SaaS used by contractors, owners, and specialty trades.",
    "MNDY": "Monday.com — work operating system and project management software used by cross-functional teams.",
    "TOST": "Toast — restaurant-focused point-of-sale and management platform with payments and payroll.",
    "ZI": "ZoomInfo — B2B sales intelligence platform providing contact data, intent signals, and workflow tools.",
    "ESTC": "Elastic — open-source-derived search and observability platform behind Elasticsearch and Kibana.",
    "DOCN": "DigitalOcean — developer-focused cloud provider offering simple compute, storage, and managed services.",
    "GTLB": "GitLab — integrated DevSecOps platform combining source control, CI/CD, and security scanning.",
    "IOT": "Samsara — connected operations platform for fleets, equipment, and industrial workflows.",
    "BRZE": "Braze — customer engagement platform for cross-channel marketing automation and lifecycle messaging.",
    "KVYO": "Klaviyo — marketing automation and customer data platform focused on e-commerce brands.",
    "SMAR": "Smartsheet — collaborative work execution platform combining spreadsheets with project management.",
    "APPF": "AppFolio — vertical SaaS for property management and legal practice management.",
    "TENB": "Tenable — vulnerability management platform known for Nessus and cloud security posture management.",
    "QLYS": "Qualys — cloud-based vulnerability management, compliance, and web application scanning platform.",
    "CYBR": "CyberArk — identity security leader specializing in privileged access management.",
    "RPD": "Rapid7 — security operations platform spanning vulnerability management, SIEM, and detection response.",
    "FRSH": "Freshworks — customer and employee experience software competing with Zendesk and ServiceNow.",
    "ADSK": "Autodesk — CAD and engineering software used in architecture, construction, manufacturing, and media.",
    "ANSS": "Ansys — engineering simulation software spanning mechanical, electromagnetic, and fluid dynamics.",
    "TEAM": "Atlassian — maker of Jira, Confluence, and collaboration tools for software and business teams.",
    "INTU": "Intuit — owner of TurboTax, QuickBooks, Credit Karma, and Mailchimp across consumer and SMB finance.",
    "CDNS": "Cadence Design Systems — electronic design automation tools used by semiconductor designers.",
    "SNPS": "Synopsys — electronic design automation and IP licensing for advanced-node chip design.",

    # Energy
    "XOM": "ExxonMobil — integrated oil and gas supermajor with upstream, refining, and chemicals operations.",
    "CVX": "Chevron — integrated oil and gas supermajor with upstream, downstream, and LNG exposure.",
    "OXY": "Occidental Petroleum — oil and gas producer concentrated in the Permian Basin with carbon capture ventures.",
    "DVN": "Devon Energy — US shale-focused oil and gas producer with Permian and Anadarko exposure.",
    "FANG": "Diamondback Energy — pure-play Permian Basin oil and gas producer.",
    "MPC": "Marathon Petroleum — US refining leader with midstream and retail (Speedway) exposure.",
    "VLO": "Valero Energy — largest US independent refiner with renewable diesel and ethanol operations.",
    "HAL": "Halliburton — oilfield services provider specializing in hydraulic fracturing and drilling.",
    "SLB": "Schlumberger — largest global oilfield services company offering reservoir, drilling, and production services.",
    "EOG": "EOG Resources — US independent E&P focused on horizontal shale oil and gas production.",
    "PXD": "Pioneer Natural Resources — Permian-focused independent oil and gas producer (acquired by ExxonMobil).",
    "AR": "Antero Resources — Appalachian natural gas and NGL producer with significant LNG export exposure.",
    "RRC": "Range Resources — Appalachian natural gas and NGL producer focused on the Marcellus Shale.",
    "CTRA": "Coterra Energy — diversified US E&P with Permian, Marcellus, and Anadarko operations.",
    "OVV": "Ovintiv — US and Canadian oil and gas producer with Permian, Anadarko, and Montney exposure.",
    "SM": "SM Energy — independent E&P focused on Midland Basin and South Texas oil and gas production.",

    # Financials
    "GS": "Goldman Sachs — investment bank with trading, M&A advisory, asset management, and consumer banking.",
    "MS": "Morgan Stanley — investment bank with large wealth management platform and institutional trading.",
    "JPM": "JPMorgan Chase — largest US bank with investment banking, consumer banking, and asset management.",
    "C": "Citigroup — global bank with institutional services, wealth, and personal banking across 95+ countries.",
    "BAC": "Bank of America — US consumer banking leader with wealth management and investment banking arms.",
    "ARES": "Ares Management — alternative asset manager focused on private credit, real estate, and private equity.",
    "APO": "Apollo Global Management — alternative asset manager with large private credit and insurance platform (Athene).",
    "BX": "Blackstone — largest alternative asset manager across private equity, real estate, credit, and hedge funds.",
    "KKR": "KKR — alternative asset manager spanning private equity, credit, infrastructure, and insurance.",
    "OWL": "Blue Owl — alternative asset manager specializing in direct lending and GP-minority stakes.",
    "SOFI": "SoFi — digital financial services platform offering lending, banking, and investing to consumers.",
    "HOOD": "Robinhood — commission-free retail brokerage with crypto, options, and expanding wealth products.",
    "UPST": "Upstart — AI-driven consumer lending marketplace partnering with banks on unsecured personal loans.",
    "LC": "LendingClub — digital bank offering personal loans, auto refinancing, and deposit products.",
    "NU": "Nu Holdings — Latin American digital bank serving 90M+ customers across Brazil, Mexico, and Colombia.",

    # Healthcare / Biotech
    "MRNA": "Moderna — mRNA-platform biotech best known for its COVID vaccine with broader infectious disease pipeline.",
    "BNTX": "BioNTech — mRNA-platform biotech partnered with Pfizer on COVID and developing oncology candidates.",
    "CRSP": "CRISPR Therapeutics — gene-editing biotech with approved sickle cell therapy (Casgevy) and broader pipeline.",
    "NTLA": "Intellia Therapeutics — in-vivo CRISPR gene-editing biotech advancing therapies for ATTR amyloidosis and HAE.",
    "BEAM": "Beam Therapeutics — base-editing gene therapy company with pipeline across sickle cell and oncology.",
    "EDIT": "Editas Medicine — gene-editing biotech developing CRISPR-based therapies for rare genetic diseases.",
    "EXAS": "Exact Sciences — cancer screening company behind the Cologuard stool DNA colorectal cancer test.",
    "SGEN": "Seagen — antibody-drug conjugate oncology company (acquired by Pfizer in 2023).",
    "IONS": "Ionis Pharmaceuticals — RNA-targeted drug developer with neuro, cardiovascular, and rare disease pipeline.",
    "SRPT": "Sarepta Therapeutics — gene therapy company focused on Duchenne muscular dystrophy.",
    "VRTX": "Vertex Pharmaceuticals — cystic fibrosis leader expanding into sickle cell, pain, and type 1 diabetes.",
    "REGN": "Regeneron — biotech behind Eylea (ophthalmology) and Dupixent (immunology), with strong oncology pipeline.",
    "BIIB": "Biogen — neurology-focused biotech with MS franchise and Alzheimer's (Leqembi) partnership with Eisai.",
    "HIMS": "Hims & Hers Health — direct-to-consumer telehealth platform for personal care, mental health, and GLP-1 weight loss.",

    # Consumer Discretionary
    "ABNB": "Airbnb — global marketplace for short-term rentals and experiences with hosts in 220+ countries.",
    "DASH": "DoorDash — largest US on-demand delivery platform for restaurants, groceries, and retail.",
    "UBER": "Uber — global rideshare and delivery platform with mobility, delivery, and freight segments.",
    "LYFT": "Lyft — US rideshare platform competing with Uber in mobility.",
    "W": "Wayfair — online retailer specializing in home goods and furniture.",
    "ETSY": "Etsy — online marketplace for handmade, vintage, and craft goods sold by independent sellers.",
    "PTON": "Peloton — connected fitness company selling bikes, treadmills, and subscription workout content.",
    "RIVN": "Rivian — EV manufacturer producing the R1T pickup, R1S SUV, and Amazon delivery vans.",
    "LCID": "Lucid Motors — luxury EV manufacturer producing the Air sedan with Saudi PIF as majority backer.",
    "NIO": "NIO — Chinese EV manufacturer known for premium SUVs and battery-swap infrastructure.",
    "XPEV": "XPeng — Chinese EV manufacturer focused on smart EVs with advanced driver assistance.",
    "LI": "Li Auto — Chinese EV manufacturer specializing in range-extender SUVs.",
    "CVNA": "Carvana — online used car retailer with automated vending machines and nationwide logistics.",
    "CART": "Maplebear (Instacart) — online grocery delivery platform with retail media advertising business.",

    # Industrials
    "BA": "Boeing — commercial and defense aerospace manufacturer producing 737, 787, and military platforms.",
    "CAT": "Caterpillar — leading heavy equipment maker for construction, mining, and energy.",
    "DE": "Deere & Company — agricultural and construction equipment manufacturer with precision farming tech.",
    "GE": "GE Aerospace — jet engine manufacturer following the split of GE's power and healthcare businesses.",
    "RTX": "RTX — defense and aerospace conglomerate (Raytheon + Collins Aerospace + Pratt & Whitney).",
    "LMT": "Lockheed Martin — largest US defense contractor producing F-35s, missiles, and space systems.",
    "NOC": "Northrop Grumman — defense prime contractor in aeronautics, space, and missile systems.",
    "AXON": "Axon Enterprise — maker of Tasers and body cameras with fast-growing cloud evidence software.",
    "TDG": "TransDigm — highly acquisitive aerospace aftermarket parts supplier with strong pricing power.",
    "BLDE": "Blade Air Mobility — short-haul urban air mobility operator across helicopter and eVTOL partnerships.",
    "JOBY": "Joby Aviation — eVTOL developer building electric air taxis for urban commuter routes.",
    "LUNR": "Intuitive Machines — lunar exploration company providing lander services to NASA's Artemis program.",
    "RDW": "Redwire — space infrastructure company providing payloads, solar arrays, and in-space manufacturing.",

    # Materials
    "NEM": "Newmont — largest gold mining company globally with copper and silver by-product exposure.",
    "FCX": "Freeport-McMoRan — major copper and gold miner with the Grasberg mine in Indonesia.",
    "GOLD": "Barrick Gold — global gold mining major with significant copper exposure.",
    "AEM": "Agnico Eagle Mines — senior gold producer with operations across Canada, Mexico, Finland, and Australia.",
    "WPM": "Wheaton Precious Metals — precious metals streaming company with silver and gold exposure.",
    "VALE": "Vale — Brazilian mining giant and second-largest iron ore producer globally.",
    "RIO": "Rio Tinto — global mining major focused on iron ore, aluminum, copper, and lithium.",
    "BHP": "BHP Group — global diversified mining company focused on iron ore, copper, and potash.",
    "CLF": "Cleveland-Cliffs — largest flat-rolled steel producer in North America with iron ore mining.",
    "X": "US Steel — integrated North American steel producer (being acquired by Nippon Steel).",
    "AA": "Alcoa — integrated aluminum producer spanning bauxite mining, alumina refining, and smelting.",
    "MP": "MP Materials — operator of Mountain Pass, the largest rare earth mine in the Western Hemisphere.",
    "LAC": "Lithium Americas — lithium developer advancing the Thacker Pass mine in Nevada.",
    "ALB": "Albemarle — largest global lithium producer, supplying EV battery cathodes and specialty chemicals.",

    # Communication Services
    "META": "Meta Platforms — parent of Facebook, Instagram, and WhatsApp with major AI and Reality Labs investments.",
    "GOOGL": "Alphabet — parent of Google Search, YouTube, Android, and Google Cloud.",
    "SNAP": "Snap — parent of Snapchat with AR ad tools and Spectacles hardware.",
    "PINS": "Pinterest — visual discovery and shopping platform with 500M+ monthly users.",
    "RDDT": "Reddit — user-generated forum platform monetizing via ads and data licensing to AI companies.",
    "SPOT": "Spotify — largest global audio streaming platform with music, podcasts, and audiobooks.",
    "ROKU": "Roku — connected TV operating system and ad-supported streaming hub.",
    "TTD": "The Trade Desk — independent demand-side platform for programmatic CTV and digital advertising.",
    "DIS": "Disney — media conglomerate with theme parks, studios, ESPN, and Disney+ streaming.",
    "NFLX": "Netflix — global subscription video streaming leader with expanding ad-supported tier.",
    "RBLX": "Roblox — user-generated gaming platform with 80M+ daily active users.",
    "BMBL": "Bumble — female-first dating app with Bumble Date and Bumble for Friends verticals.",
}


def get_description(symbol: str) -> str:
    """Return a description for a ticker, or a generic fallback."""
    return DESCRIPTIONS.get(symbol.upper(), f"{symbol.upper()} — publicly traded US equity.")
